version: 0.2
phases:
  pre_build:
    commands:
      - echo "In the pre_build phase..."
      - ls -l DemoProd/node_modules || echo "No cache restored"
  build:
    commands:
      - echo "In the build phase..."
      - cd DemoProd/
      - echo "Installing dependencies..."
      - npm ci
      - echo "Installing dependencies done!"
  php-test:
    commands:
      - echo "In the php-test phase..." 
      - php -v
      - composer -v
  post_build:
    commands:
      - echo "In the post_build phase..."
cache:
  paths:
    - DemoProd/node_modules/**/*
    - DemoProd/controllers/**/*
    - DemoProd/middlewares/**/*
    - DemoProd/routes/**/*