version: 0.2
phases:
  pre_build:
    commands:
      - echo "In the pre_build phase..."
  build:
    commands:
      - echo "In the build phase..."
      - cd DemoProd/
      - echo "Installing dependencies..."
      - npm install
      - npm install chalk
      - npm install lodash
      - echo "Installing dependencies done!"
  post_build:
    commands:
      - echo "In the post_build phase..."
cache:
  paths:
    - 'DemoProd/node_modules/**/*' 
